name: Generate Last-Commit Badge (MM/DD/YY)
on:
  push:
    branches: [ main ]   # change if your default branch is different
  workflow_dispatch:

jobs:
  generate-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get last commit ISO timestamp
        id: lastcommit
        run: |
          # get ISO 8601 commit date of HEAD
          iso=$(git log -1 --format=%cI)
          echo "iso=$iso" >> $GITHUB_OUTPUT

      - name: Format date MM/DD/YY
        id: fmt
        run: |
          iso="${{ steps.lastcommit.outputs.iso }}"
          # convert to MM/DD/YY
          formatted=$(date -d "$iso" +"%m/%d/%y")
          echo "formatted=$formatted" >> $GITHUB_OUTPUT

      - name: Create SVG badge (simple)
        id: make_svg
        run: |
          D="${{ steps.fmt.outputs.formatted }}"
          # Choose colors / label / font-size here as needed
          cat > last-commit-badge.svg <<'SVG'
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="20" role="img" aria-label="Last commit">
  <rect width="80" height="20" fill="#555"/>
  <rect x="80" width="120" height="20" fill="#1577ff"/>
  <g fill="#fff" font-family="Verdana,Arial,sans-serif" font-size="11">
    <text x="8" y="14" fill="#fff">last</text>
    <text x="98" y="14" fill="#fff">REPLACE_DATE</text>
  </g>
</svg>
SVG
          # inject formatted date (escape any slashes)
          sed -i "s/REPLACE_DATE/${D//\//\\/}/g" last-commit-badge.svg
          ls -l last-commit-badge.svg
          echo "::set-output name=svgfile::last-commit-badge.svg"

      - name: Commit and push badge (if changed)
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git add last-commit-badge.svg || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore: update last-commit badge to ${{ steps.fmt.outputs.formatted }}" || true
          git push origin HEAD:${{ github.ref_name }}
          
