name: Update Last Commit Badge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: true  # keep credentials for pushing

      - name: Get last commit date and format as MM/DD/YY
        id: lastcommit
        run: |
          # Get most recent commit date in ISO 8601 format
          dt_iso=$(git log -1 --format=%cd --date=iso-strict)
          # Format to MM/DD/YY using date command
          formatted_date=$(date -d "$dt_iso" +"%m/%d/%y")
          echo "last_commit_date=$formatted_date" >> $GITHUB_OUTPUT

      - name: Create SVG badge file last-commit-badge.svg
        run: |
          cat > last-commit-badge.svg << 'EOF'
          <svg xmlns="http://www.w3.org/2000/svg" width="115" height="20">
            <linearGradient id="s" x2="0" y2="100%">
              <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
              <stop offset="1" stop-opacity=".1"/>
            </linearGradient>
            <mask id="m">
              <rect width="115" height="20" rx="3" fill="#fff"/>
            </mask>
            <g mask="url(#m)">
              <rect width="65" height="20" fill="#555555"/>
              <rect x="65" width="50" height="20" fill="#1577ff"/>
              <rect width="115" height="20" fill="url(#s)"/>
            </g>
            <g fill="#fff" text-anchor="middle" font-family="Verdana" font-size="11">
              <text x="32.5" y="14" fill="#fff">last commit</text>
              <text x="90" y="14" fill="#fff">${{ steps.lastcommit.outputs.last_commit_date }}</text>
            </g>
          </svg>
          EOF

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push badge if changed
        run: |
          git add last-commit-badge.svg
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update last-commit-badge.svg to ${{ steps.lastcommit.outputs.last_commit_date }}"
            git push origin main
          fi<svg xmlns="http://www.w3.org/2000/svg" width="200" height="20" role="img" aria-label="Last commit">
  <rect width="80" height="20" fill="#555"/>
  <rect x="80" width="120" height="20" fill="#1577ff"/>
  <g fill="#fff" font-family="Verdana,Arial,sans-serif" font-size="11">
    <text x="8" y="14" fill="#fff">last</text>
    <text x="98" y="14" fill="#fff">REPLACE_DATE</text>
  </g>
</svg>
SVG
          # inject formatted date (escape any slashes)
          sed -i "s/REPLACE_DATE/${D//\//\\/}/g" last-commit-badge.svg
          ls -l last-commit-badge.svg
          echo "::set-output name=svgfile::last-commit-badge.svg"

      - name: Commit and push badge (if changed)
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git add last-commit-badge.svg || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore: update last-commit badge to ${{ steps.fmt.outputs.formatted }}" || true
          git push origin HEAD:${{ github.ref_name }}
          
